<a href="https://colab.research.google.com/github/aayushbagrecha/TSPtasks/blob/master/TSP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Task # 4 - To Explore Decision Tree Algorithm

For the given ‘Iris’ dataset, create the Decision Tree classifier and
visualize it graphically. The purpose is if we feed any new data to this
classifier, it would be able to predict the right class accordingly.

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('TSP2.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)

[[1.38e+02 6.40e+00 3.10e+00 5.50e+00 1.80e+00]
 [8.50e+01 5.40e+00 3.00e+00 4.50e+00 1.50e+00]
 [2.80e+01 5.20e+00 3.50e+00 1.50e+00 2.00e-01]
 [1.28e+02 6.10e+00 3.00e+00 4.90e+00 1.80e+00]
 [1.33e+02 6.40e+00 2.80e+00 5.60e+00 2.20e+00]
 [6.00e+01 5.20e+00 2.70e+00 3.90e+00 1.40e+00]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [8.40e+01 6.00e+00 2.70e+00 5.10e+00 1.60e+00]
 [6.20e+01 5.90e+00 3.00e+00 4.20e+00 1.50e+00]
 [9.30e+01 5.80e+00 2.60e+00 4.00e+00 1.20e+00]
 [1.13e+02 6.80e+00 3.00e+00 5.50e+00 2.10e+00]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [1.42e+02 6.90e+00 3.10e+00 5.10e+00 2.30e+00]
 [4.40e+01 5.00e+00 3.50e+00 1.60e+00 6.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [6.10e+01 5.00e+00 2.00e+00 3.50e+00 1.00e+00]
 [1.17e+02 6.50e+00 3.00e+00 5.50e+00 1.80e+00]
 [1.45e+02 6.70e+00 3.30e+00 5.70e+00 2.50e+00]
 [1.20e+02 6.00e+00 2.20e+00 5.00e+00 1.50e+00]
 [1.09e+02 6.70e+00 2.50e+00 5.80e+00 1.80e+00]
 [7.00e+01 5.60e+00 2.50e+00 3.90e+00 1.

In [ ]:
print(X_test)

[[1.15e+02 5.80e+00 2.80e+00 5.10e+00 2.40e+00]
 [6.30e+01 6.00e+00 2.20e+00 4.00e+00 1.00e+00]
 [3.40e+01 5.50e+00 4.20e+00 1.40e+00 2.00e-01]
 [1.08e+02 7.30e+00 2.90e+00 6.30e+00 1.80e+00]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [1.01e+02 6.30e+00 3.30e+00 6.00e+00 2.50e+00]
 [4.10e+01 5.00e+00 3.50e+00 1.30e+00 3.00e-01]
 [8.70e+01 6.70e+00 3.10e+00 4.70e+00 1.50e+00]
 [7.70e+01 6.80e+00 2.80e+00 4.80e+00 1.40e+00]
 [7.20e+01 6.10e+00 2.80e+00 4.00e+00 1.30e+00]
 [1.35e+02 6.10e+00 2.60e+00 5.60e+00 1.40e+00]
 [5.20e+01 6.40e+00 3.20e+00 4.50e+00 1.50e+00]
 [7.40e+01 6.10e+00 2.80e+00 4.70e+00 1.20e+00]
 [5.50e+01 6.50e+00 2.80e+00 4.60e+00 1.50e+00]
 [6.40e+01 6.10e+00 2.90e+00 4.70e+00 1.40e+00]
 [3.80e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [7.90e+01 6.00e+00 2.90e+00 4.50e+00 1.50e+00]
 [9.10e+01 5.50e+00 2.60e+00 4.40e+00 1.20e+00]
 [4.60e+01 4.80e+00 3.00e+00 1.40e+00 3.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.22e+02 5.60e+00 2.80e+00 4.90e+00 2.

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


0.9666666666666667